src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Resume\Resume;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\DBAL\Types\Types;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['email'], message: 'L\'adresse email est déjà utilisée.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /**
     * Coordonnées
     */
    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column()]
    private ?int $zipCode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(length: 255)]
    private ?string $region = null;

    #[ORM\Column(length: 255)]
    private ?string $department = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    /**
     * Design attributes
     */

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePicture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bannerPicture = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $publicDescription = "Pas de description";

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;


    /**
     * Business
     */

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $siret = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Offer::class)]
    private Collection $offers;


    /**
     * Person
     */

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastName = null;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Resume $resume = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateOfBirth = null;

    #[ORM\OneToMany(mappedBy: 'applicant', targetEntity: Demands::class)]
    private Collection $demands;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Notification::class, orphanRemoval: true)]
    private Collection $notifications;

    

    


    public function __construct()
    {
        $this->offers = new ArrayCollection();
        $this->demands = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function prePersist()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
    
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole($role): self
    {
        $this->roles[] = $role;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    
    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zipCode;
    }

    public function setZipCode(?int $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture == null ? "user.png" : $this->profilePicture;
    }

    public function setProfilePicture(string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function getBannerPicture(): ?string
    {
        return $this->bannerPicture == null ? ".default-banner.png" : $this->bannerPicture;
    }

    public function setBannerPicture(?string $bannerPicture): self
    {
        $this->bannerPicture = $bannerPicture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }


    /**
     * Business
    */

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    /**
     * @return Collection<int, Offer>
     */
    public function getOffers(): Collection
    {
        return $this->offers;
    }

    public function addOffer(Offer $offer): self
    {
        if (!$this->offers->contains($offer)) {
            $this->offers->add($offer);
            $offer->setUser($this);
        }

        return $this;
    }

    public function removeOffer(Offer $offer): self
    {
        if ($this->offers->removeElement($offer)) {
            // set the owning side to null (unless already changed)
            if ($offer->getUser() === $this) {
                $offer->setUser(null);
            }
        }

        return $this;
    }


    /**
     * Person
     */

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getResume(): ?Resume
    {
        return $this->resume;
    }

    public function setResume(?Resume $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->dateOfBirth;
    }

    public function setDateOfBirth(\DateTimeInterface $dateOfBirth): self
    {
        $this->dateOfBirth = $dateOfBirth;

        return $this;
    }

    /**
     * @return Collection<int, Demands>
     */
    public function getDemands(): Collection
    {
        return $this->demands;
    }

    public function addDemand(Demands $demand): self
    {
        if (!$this->demands->contains($demand)) {
            $this->demands->add($demand);
            $demand->setApplicant($this);
        }

        return $this;
    }

    public function removeDemand(Demands $demand): self
    {
        if ($this->demands->removeElement($demand)) {
            // set the owning side to null (unless already changed)
            if ($demand->getApplicant() === $this) {
                $demand->setApplicant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {

src/Controller/Business/OfferController.php
<?php
namespace App\Controller\Business;

use App\Entity\Offer;
use App\Form\OfferType;
use App\Entity\Category;
use App\Service\Applications\Applications;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use PhpParser\Node\Stmt\Catch_;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class OfferController extends AbstractController
{
    #[Route('/offres', name: 'app_offer_list')]
    public function list(ManagerRegistry $doctrine) : Response
    {
        $Offers = $doctrine->getRepository(Offer::class)->findBy(['isArchived' => 0]);
        $categories = $doctrine->getRepository(Category::class)->findAll();

        return $this->render('offer/list.html.twig', 
        [
            'Offers' => $Offers,
            "Categories" => $categories
        ]);
    }

    #[Route('/offres/filter/{id}', name: 'app_offer_filter')]
    public function filterOffer(ManagerRegistry $doctrine, Category $category) : Response
    {
        $Offers = $doctrine->getRepository(Offer::class)->findByCategory($category);
        $categories = $doctrine->getRepository(Category::class)->findAll();
        return $this->render('offer/list.html.twig', 
        [
            'Offers' => $Offers,
            "Categories" => $categories
        ]);
    }

    #[Route('/offres/{id}', name: 'app_offer_detail')]
    public function detail(EntityManagerInterface $entityManager, Request $request, ManagerRegistry $doctrine, Applications $applications, Offer $oneOffer): Response
    {
        $oneOffer = $doctrine->getRepository(Offer::class)->findOneBy(['id' => $oneOffer->getId()]);
        $duration = $oneOffer->getDuration();
        $dateInterval = 0;
        if($duration != null)
        {
            $years = $duration->format('%Y années');
            $month = $duration->format('%M mois');
            $days = $duration->format('%D jours');
            $dateInterval = $days . " " . $month . " " . $years . " ";
        }
        
        

        if(!$this->getUser() || !in_array("ROLE_BUSINESS",$this->getUser()->getRoles()))
        {
            $oneOffer->setViews($oneOffer->getViews() + 1);
            $entityManager->persist($oneOffer);
            $entityManager->flush();
        }
        
        if ($request->isMethod('POST'))
        {
            if ($this->isGranted("ROLE_USER"))
            {
                $success = $applications->create($oneOffer, $this->getUser());

                if ($success)
                {
                    $message = "<strong>Confirmé !</strong> La candidature a bien été déposé.";
                    $messageType = 'success';
                }
                else
                {
                    $message = "<strong>Erreur !</strong> Vous avez déjà déposé votre candidature !";
                    $messageType = 'danger';
                }
            }
        }

        return $this->render('offer/detail.html.twig',
            [
                'oneOffer' => $oneOffer,
                'duration' => $dateInterval,
                'message' => $message ?? null,
                'messageType' => $messageType ?? null,
            ]);
    }

    #[IsGranted("ROLE_BUSINESS")]
    #[Route('pro/offres/deposer', name: 'app_offer_create')]
    public function add(Request $request, ManagerRegistry $doctrine): Response
    {
        $entityManager = $doctrine->getManager();
        $offer = new Offer();

        $form = $this->createForm(OfferType::class, $offer);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid())
        {
            if($offer->getstartAt() != null && $offer->getEndAt())
            {
                $offer->setDuration(date_diff($offer->getstartAt(),$offer->getEndAt()));
            }

            $offer->setUser($this->getUser());
            
            
            $entityManager->persist($offer);
            $entityManager->flush();

            return $this->redirectToRoute("app_offer_detail", [ "id" => $offer->getId() ]);
        }

        return $this->render('business/offer/create.html.twig',
        [
            'Offer' => $form->createView(),
        ]);
    }

    #[IsGranted("ROLE_BUSINESS")]
    #[Route('pro/mes-offres', name: 'app_business_offer_list')]
    public function myOffers(Request $request, ManagerRegistry $doctrine): Response
    {
        return $this->render('business/offer/list.html.twig',
    [
        "offres_archived" => $doctrine->getRepository(Offer::class)->findBy(["isArchived" => 1,"user" => $this->getUser()]) 
    ]);
    }

    #[IsGranted("ROLE_BUSINESS")]
    #[Route('pro/offres/{id}/modifier', name: 'app_offer_edit')]
    public function edit(Request $request, ManagerRegistry $doctrine, Offer $oneOffer): Response
    {
        if($this->getUser() === $oneOffer->getUser())
        {
            if(!$oneOffer->IsArchived())
            {
                $entityManager = $doctrine->getManager();
                $form = $this->createForm(OfferType::class, $oneOffer);
                $form->handleRequest($request);
                if($form->isSubmitted() && $form->isValid())
                {
                    $oneOffer->setUser($this->getUser());
                    if($oneOffer->getstartAt() != null && $oneOffer->getEndAt())
                    {
                        $oneOffer->setDuration(date_diff($oneOffer->getstartAt(),$oneOffer->getEndAt()));
                    }
                    $oneOffer->setCreatedAt(new DateTimeImmutable());
                    $oneOffer = $form->getData();
                    $entityManager->flush();
                    return $this->redirectToRoute("app_offer_detail",
                    [
                        'id' => $oneOffer->getId()
                    ]);
                }
                return $this->render('business/offer/create.html.twig', 
                [
                    'Offer' => $form->createView(),
                ]);
            }
        }
        return $this->redirectToRoute("app_offer_list");
    }

    #[IsGranted("ROLE_BUSINESS")]
    #[Route('/pro/offres/{id}/supprimer', name: 'app_offer_delete')]
    public function delete(ManagerRegistry $doctrine, Offer $oneOffer): Response
    {
        if($oneOffer->getUser() === $this->getUser())
        {
            $manager = $doctrine->getManager();
            $oneOffer->setIsArchived(true);
            $manager->persist($oneOffer);
            $manager->flush();
            return $this->redirectToRoute('app_offer_list');
        }
        return $this->redirectToRoute('app_offer_list');
    }
}

templates/business/base.html.twig
{% extends 'base.html.twig' %}

{% block home %}

    <div id="header-wrap" class="border-top border-f5 z-1">
        <div class="container">
            <div class="header-row justify-content-between flex-row-reverse flex-lg-row top-search-parent">
                <nav class="primary-menu style-6">
                    <ul class="menu-container">
                        <li class="menu-item"><a class="menu-link" href="{{ path('app_business_dashboard') }}">Dashboard</a></li>
                        <li class="menu-item"><a class="menu-link" href="{{ path('app_offer_create') }}">Déposer une offre</a></li>
                        <li class="menu-item"><a class="menu-link" href="{{ path('app_business_offer_list') }}">Mes offres</a></li>
                        <li class="menu-item"><a class="menu-link" href="{{ path('app_business_profile_public') }}">Profil public</a></li>
                        <li class="menu-item"><a class="menu-link" href="#">Paramètrer</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}

templates/business/compte.html.twig
{% extends 'business/base.html.twig' %}

{% block body %}	
	<section>
		<div class="container py-5">
			<div class="row">
				<div class="col-lg-4">
					<div class="card mb-4">
						<div class="card-body text-center">
							<img src="{{ asset('assets/images/pp/' ~ app.user.profilePicture) }}" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
							<div class="col">
								<div class="my-2">
									<h2 class="mb-0">{{business.name}}</h2>
								</div>
							<div class="hstack gap-5 text-muted">
								<div>
									<i class="bi bi-award-fill"></i>
									<span class="">
									{% if business.verified %}
										Vérifié
									{% else %}
										Pas Vérifié
									</span>
									{% endif %}
								</div>
								<div>
									<i class="bi bi-bar-chart-fill"></i>
									89%
								</div>
								<div>
									<i class="bi bi-calendar-check-fill"></i>
									{{business.createdAt |date("M/Y")}}
								</div>
							</div>

						<div class="mt-2">
							<p>{{business.publicDescription}}</p>
						</div>
					</div>
							<div class="d-flex justify-content-center mb-2">
								<button type="button" class="btn btn-primary">Editer le profil public</button>
								{# <button type="button" class="btn btn-outline-primary ms-1"></button> #}
							</div>
						</div>
					</div>
					{# <div class="card mb-4 mb-lg-0">
					          <div class="card-body p-0">
					            <ul class="list-group list-group-flush rounded-3">
					              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
					                <i class="fas fa-globe fa-lg text-warning"></i>
					                <p class="mb-0">https://mdbootstrap.com</p>
					              </li>
					              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
					                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
					                <p class="mb-0">mdbootstrap</p>
					              </li>
					              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
					                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
					                <p class="mb-0">@mdbootstrap</p>
					              </li>
					              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
					                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
					                <p class="mb-0">mdbootstrap</p>
					              </li>
					              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
					                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
					                <p class="mb-0">mdbootstrap</p>
					              </li>
					            </ul>
					          </div>
					        </div> #}
				</div>

				<div class="col-lg-8">
					<div class="card mb-4">
						<div class="card-body">
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Adresse :</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">{{business.address}}|{{business.city}}, {{business.zipCode}}</p>
								</div>
							</div>
							<hr>
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Région :
									</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">{{business.region}}</p>
								</div>
							</div>
							<hr>
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Département :
									</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">{{business.department}}</p>
								</div>
							</div>
							<hr>
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Pays :
									</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">{{business.country}}</p>
								</div>
							</div>
							<hr>
							<div class="row">
								<div class="col-sm-3">
									<p class="mb-0">Siret :
									</p>
								</div>
								<div class="col-sm-9">
									<p class="text-muted mb-0">{{business.siret}}</p>
								</div>
							</div>
						</div>
					</div>

				</div>

				<div class="col-lg-12">
					<div class="row">
						{% for offer in offers %}
							<div class="col-md-4">
								<div class="card mb-4 mb-md-0">
									<div class="card-body">
										<div class="row">
											<div class="col-sm-9">
												<p class="text-muted mb-0">{{offer.label}}</p>
											</div>
										</div>
										<div class="row">
											<div class="col-sm-9">
												<p class="text-muted mb-0">Salaire de l'heure : {{offer.moneyPerHour}} €/h</p>
											</div>
										</div>
										<div class="row">
											<div class="col-sm-9">
												<p class="text-muted mb-0">{{ offer.description|length > 100 ? offer.description|slice(0, 100) ~ '...' : offer.description  }}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/business/editer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}

{{ form_start(form) }}

    {{ form_rest(form) }}

    <button type="submit" class="btn btn-secondary">Enregistrer</button>

{{ form_end(form) }}

{% endblock %}